name: sporty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  #most powerful and awesome state management (GETX)
  get: ^4.6.0
  
  #otp textfield (awesome package)
  flutter_otp_text_field: ^1.1.1
  #another nice alternative
  otp_text_field: ^1.1.3

  
  #ui customizations
  google_fonts: ^6.0.0
  dots_indicator: ^2.1.1
  flutter_svg: ^2.0.7
  timeago: ^3.6.1
  gradient_elevated_button: ^1.0.0

  
  #for nice loadimg animation
  loading_animation_widget: ^1.2.0+4
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.0.0+2


  #country pickers
  country_code_picker: ^3.0.0
  country_picker: ^2.0.22


  #for local storage (Better than SharedPreference)
  get_storage: ^2.0.3


  #for converting date/time objects nicely including servertime stamps
  date_time_format: ^2.0.1


  #for network calls and jwt decoder
  http: ^1.1.2
  dio: ^5.5.0+1
  jwt_decoder: ^2.0.1

  #to check everything about your jwt and manage session expiry
  flutter_session_jwt: ^0.0.6

  #for google auth
  google_sign_in: ^6.1.6
  
  #screen util
  flutter_screenutil: ^5.9.0


  #firebase apis
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  googleapis_auth: ^1.6.0
  firebase_auth: ^4.15.0

  #(foreground)local notifications
  flutter_local_notifications: ^17.2.2

  #rename the app
  rename: ^3.0.2

dependency_overrides:
  intl: ^0.18.0
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  #for updating launcher icons
  flutter_launcher_icons: ^0.13.1
  #change app manifest/info.plist package name
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  #android: "launcher_icon"
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon_logo.png"




flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/




